### ISSUE TITLE
License

### ISSUE THREAD

**Issue by willem66745** [jarmol/suncalcs#1]
Can you please clarify under which license you have publish your work? I assume it is public domain, although I couldn't any statement in https://github.com/jarmol/suncalcs/blob/master/azimalt.cpp (a updated version of http://www.sci.fi/~benefon/rscalc.c).

I ask you this, since I have created a version in Rust https://github.com/willem66745/daylight-rust (strongly based on the C implementation), and I want to be sure I have chosen the correct license type (public domain).

**Comment by jarmol** [comment]
This is public domain so as anything else on this public account repository.
